### ISSUE TITLE
No module named 'funpy.cheb.detail'

### ISSUE THREAD

**Issue by cbm755** [adrs0049/funpy#1]
I'm running Python 3.11 on Fedora.  Steps:

1.  `pip install pylops`.
2.  `cd <dir where ReadMe.txt is>`
3.  `ipython`
4.  `import funpy`

```
import funpy
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 1
----> 1 import funpy

File ~/src/funpy.git/funpy/__init__.py:4
      2 from . import support
----> 4 from . import cheb
      6 from . import trig
      8 from . import fun

File ~/src/funpy.git/funpy/cheb/__init__.py:2
----> 2 from . detail import polyfit
      3 from . detail import polyval
      5 from . detail import standardChop

ModuleNotFoundError: No module named 'funpy.cheb.detail'
```
I see `detail.pyx` and `detail.pxd`  in `funpy/cheb/`: I guess something needs to be compiled.  The readme says this should happen automatically on first import: perhaps there is some other dependency I'm missing to make that happen?

**Comment by adrs0049** [comment]
Commit 3d64345ccb1a6f1ce94aa5e2ce6f2d04a01b2e70 should fix this issue.

Chebyshev interpolants pass their unit tests.

**Comment by adrs0049** [comment]
Closing as there now is also a seemingly working setup.py that should compile and install the cython modules. Changes in 75cb99e
